[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cw-tent-experiments"
version = "1.0.0"
description = "Confidence-Weighted TENT experiments with Hydra / Optuna / WandB"
authors = [{name = "Researcher"}]

[project.dependencies]
torch = ">=2.0"
torchvision = ">=0.15"
timm = ">=0.9"
hydra-core = ">=1.3"
wandb = ">=0.15"
optuna = ">=3.3"
numpy = "*"
pandas = "*"
scikit-learn = "*"
matplotlib = "*"
seaborn = "*"
scipy = "*"