# config/config.yaml – root Hydra configuration
# ------------------------------------------------
defaults:
  - optional run: null
  - _self_

run: default-run-id        # overridden from CLI (name of YAML inside config/run/)
results_dir: ./results     # overridden from CLI
trial_mode: false          # set to true for quick CI runs

hydra:
  run:
    dir: .
  job:
    chdir: false

wandb:
  entity: gengaru617-personal
  project: 251020-test
  mode: online             # automatically set to "disabled" in trial_mode

optuna:
  n_trials: 0              # 0 → disabled; can be overridden per-run
  direction: maximize
  metric: top1_accuracy
  search_space: {}

logging:
  log_every_n_steps: 50
