# config/config.yaml
# ==============================================================================
# Global Hydra configuration shared by *all* runs.
# ==============================================================================

defaults:
  - _self_
  - run: null          # injected via CLI, e.g.  run=proposed-ResNet-18

# ------------------------------------------------------------------------------
# Global toggles
# ------------------------------------------------------------------------------

trial_mode: false
results_dir: ./results
seed: 42

# ------------------------------------------------------------------------------
# WandB (auto-disabled in trial-mode by main.py)
# ------------------------------------------------------------------------------

wandb:
  entity: gengaru617-personal
  project: 251020-test
  mode: online

# ------------------------------------------------------------------------------
# Place-holders (overwritten by flattening helper)
# ------------------------------------------------------------------------------

model: {}
dataset: {}
training: {}
optuna: {}

# ------------------------------------------------------------------------------
# Hydra runtime dirs & logging
# ------------------------------------------------------------------------------

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}_${now:%H-%M-%S}_${run.run_id}
  job_logging:
    version: 1
    root:
      level: INFO
  hydra_logging:
    version: 1
    root:
      level: INFO