defaults:
  - _self_
  - run: proposed-ResNet-18

# Global switches -------------------------------------------------------------
trial_mode: false            # set to true via CLI for lightweight CI validation
results_dir: ./results       # can be overridden from CLI

# WandB configuration ---------------------------------------------------------
wandb:
  entity: gengaru617-personal
  project: 251020-test
  mode: online               # automatically switched to "disabled" in trial_mode

# Optuna (overwritten by run configs) -----------------------------------------
optuna:
  n_trials: 0
  direction: maximize
  metric: top1_accuracy
  search_space: {}
